export type Package = {
  name: string
  slug: string
  description: string
  version: string
  author: string
  license: string
  downloads: string
  category: string
  tags: string[]
  featured: boolean
  installCommand: string
  repositoryUrl: string
  documentationUrl: string
  lastUpdated: string
  pythonVersions: string[]
  dependencies: string[]
  longDescription: string
}

export type Category = {
  name: string
  slug: string
  description: string
  count: number
}

export const categories: Category[] = [
  { name: "All Categories", slug: "all", description: "Browse all packages", count: 24 },
  { name: "Web Frameworks", slug: "web-frameworks", description: "Build web applications with Python", count: 4 },
  { name: "Data Science", slug: "data-science", description: "Analyze and visualize data", count: 4 },
  { name: "Machine Learning", slug: "machine-learning", description: "Build intelligent models", count: 4 },
  { name: "DevOps", slug: "devops", description: "Automate deployments and infrastructure", count: 3 },
  { name: "Testing", slug: "testing", description: "Test your Python code", count: 3 },
  { name: "CLI Tools", slug: "cli-tools", description: "Build command-line interfaces", count: 3 },
  { name: "Database", slug: "database", description: "Database drivers and ORMs", count: 3 },
]

export const packages: Package[] = [
  {
    name: "FastAPI",
    slug: "fastapi",
    description: "Modern, fast web framework for building APIs with Python based on standard type hints.",
    version: "0.115.6",
    author: "Sebastian Ramirez",
    license: "MIT",
    downloads: "38.2M",
    category: "web-frameworks",
    tags: ["api", "async", "rest", "openapi"],
    featured: true,
    installCommand: "pip install fastapi",
    repositoryUrl: "https://github.com/tiangolo/fastapi",
    documentationUrl: "https://fastapi.tiangolo.com",
    lastUpdated: "2025-12-15",
    pythonVersions: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"],
    dependencies: ["starlette", "pydantic"],
    longDescription: "FastAPI is a modern, fast (high-performance), web framework for building APIs with Python 3.8+ based on standard Python type hints. It features automatic API documentation, editor support, validation, serialization, authentication, and dependency injection built-in. FastAPI is built on top of Starlette for the web parts and Pydantic for the data parts, making it one of the fastest Python frameworks available.",
  },
  {
    name: "Django",
    slug: "django",
    description: "The web framework for perfectionists with deadlines. High-level Python framework.",
    version: "5.1.4",
    author: "Django Software Foundation",
    license: "BSD-3-Clause",
    downloads: "22.8M",
    category: "web-frameworks",
    tags: ["web", "mvc", "orm", "full-stack"],
    featured: true,
    installCommand: "pip install django",
    repositoryUrl: "https://github.com/django/django",
    documentationUrl: "https://docs.djangoproject.com",
    lastUpdated: "2025-11-20",
    pythonVersions: ["3.10", "3.11", "3.12", "3.13"],
    dependencies: ["asgiref", "sqlparse"],
    longDescription: "Django is a high-level Python web framework that encourages rapid development and clean, pragmatic design. Built by experienced developers, it takes care of much of the hassle of web development, so you can focus on writing your app without needing to reinvent the wheel. It's free and open source with a thriving community.",
  },
  {
    name: "Flask",
    slug: "flask",
    description: "A lightweight WSGI web application framework. Designed to make getting started quick.",
    version: "3.1.0",
    author: "Pallets",
    license: "BSD-3-Clause",
    downloads: "41.5M",
    category: "web-frameworks",
    tags: ["web", "wsgi", "micro-framework"],
    featured: false,
    installCommand: "pip install flask",
    repositoryUrl: "https://github.com/pallets/flask",
    documentationUrl: "https://flask.palletsprojects.com",
    lastUpdated: "2025-10-05",
    pythonVersions: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"],
    dependencies: ["werkzeug", "jinja2", "click", "itsdangerous"],
    longDescription: "Flask is a lightweight WSGI web application framework. It is designed to make getting started quick and easy, with the ability to scale up to complex applications. It began as a simple wrapper around Werkzeug and Jinja and has become one of the most popular Python web application frameworks.",
  },
  {
    name: "Starlette",
    slug: "starlette",
    description: "The little ASGI framework that shines. Lightweight, ideal for high-performance async services.",
    version: "0.41.3",
    author: "Encode",
    license: "BSD-3-Clause",
    downloads: "29.1M",
    category: "web-frameworks",
    tags: ["async", "asgi", "websocket"],
    featured: false,
    installCommand: "pip install starlette",
    repositoryUrl: "https://github.com/encode/starlette",
    documentationUrl: "https://www.starlette.io",
    lastUpdated: "2025-09-18",
    pythonVersions: ["3.8", "3.9", "3.10", "3.11", "3.12"],
    dependencies: ["anyio"],
    longDescription: "Starlette is a lightweight ASGI framework/toolkit, which is ideal for building async web services in Python. It provides a production-ready foundation with WebSocket support, GraphQL support, in-process background tasks, and more.",
  },
  {
    name: "pandas",
    slug: "pandas",
    description: "Powerful data structures for data analysis, time series, and statistics.",
    version: "2.2.3",
    author: "The Pandas Development Team",
    license: "BSD-3-Clause",
    downloads: "82.6M",
    category: "data-science",
    tags: ["data", "analysis", "dataframe", "statistics"],
    featured: true,
    installCommand: "pip install pandas",
    repositoryUrl: "https://github.com/pandas-dev/pandas",
    documentationUrl: "https://pandas.pydata.org",
    lastUpdated: "2025-11-30",
    pythonVersions: ["3.9", "3.10", "3.11", "3.12", "3.13"],
    dependencies: ["numpy", "python-dateutil", "pytz"],
    longDescription: "pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool, built on top of the Python programming language. It provides data structures and functions needed to work with structured data seamlessly, including DataFrames, time series analysis, and comprehensive data alignment.",
  },
  {
    name: "NumPy",
    slug: "numpy",
    description: "Fundamental package for array computing with Python. Scientific computing essentials.",
    version: "2.2.1",
    author: "NumPy Developers",
    license: "BSD-3-Clause",
    downloads: "112.4M",
    category: "data-science",
    tags: ["array", "math", "scientific", "computing"],
    featured: true,
    installCommand: "pip install numpy",
    repositoryUrl: "https://github.com/numpy/numpy",
    documentationUrl: "https://numpy.org",
    lastUpdated: "2025-12-01",
    pythonVersions: ["3.10", "3.11", "3.12", "3.13"],
    dependencies: [],
    longDescription: "NumPy is the fundamental package for scientific computing with Python. It provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, and more.",
  },
  {
    name: "Matplotlib",
    slug: "matplotlib",
    description: "Comprehensive library for creating static, animated, and interactive visualizations.",
    version: "3.9.3",
    author: "Matplotlib Development Team",
    license: "PSF",
    downloads: "42.1M",
    category: "data-science",
    tags: ["plotting", "charts", "visualization"],
    featured: false,
    installCommand: "pip install matplotlib",
    repositoryUrl: "https://github.com/matplotlib/matplotlib",
    documentationUrl: "https://matplotlib.org",
    lastUpdated: "2025-10-28",
    pythonVersions: ["3.9", "3.10", "3.11", "3.12"],
    dependencies: ["numpy", "pillow", "cycler", "fonttools"],
    longDescription: "Matplotlib is a comprehensive library for creating static, animated, and interactive visualizations in Python. It produces publication-quality figures in a variety of hardcopy formats and interactive environments across platforms.",
  },
  {
    name: "Polars",
    slug: "polars",
    description: "Lightning-fast DataFrame library for Rust and Python. Blazingly fast data processing.",
    version: "1.17.1",
    author: "Ritchie Vink",
    license: "MIT",
    downloads: "12.3M",
    category: "data-science",
    tags: ["dataframe", "performance", "rust"],
    featured: false,
    installCommand: "pip install polars",
    repositoryUrl: "https://github.com/pola-rs/polars",
    documentationUrl: "https://docs.pola.rs",
    lastUpdated: "2025-12-10",
    pythonVersions: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"],
    dependencies: [],
    longDescription: "Polars is a lightning-fast DataFrame library/in-memory query engine. Its embarrassingly parallel execution, cache-efficient algorithms and expressive API makes it perfect for efficient data wrangling, data pipelines, snappy APIs and more.",
  },
  {
    name: "scikit-learn",
    slug: "scikit-learn",
    description: "Machine learning in Python. Simple and efficient tools for predictive data analysis.",
    version: "1.6.0",
    author: "scikit-learn developers",
    license: "BSD-3-Clause",
    downloads: "48.9M",
    category: "machine-learning",
    tags: ["ml", "classification", "regression", "clustering"],
    featured: true,
    installCommand: "pip install scikit-learn",
    repositoryUrl: "https://github.com/scikit-learn/scikit-learn",
    documentationUrl: "https://scikit-learn.org",
    lastUpdated: "2025-11-15",
    pythonVersions: ["3.9", "3.10", "3.11", "3.12", "3.13"],
    dependencies: ["numpy", "scipy", "joblib", "threadpoolctl"],
    longDescription: "scikit-learn is a Python module for machine learning built on top of SciPy and is distributed under the 3-Clause BSD license. It features various classification, regression and clustering algorithms including support vector machines, random forests, gradient boosting, k-means and DBSCAN.",
  },
  {
    name: "PyTorch",
    slug: "pytorch",
    description: "Tensors and dynamic neural networks in Python with strong GPU acceleration.",
    version: "2.5.1",
    author: "Meta AI",
    license: "BSD-3-Clause",
    downloads: "18.7M",
    category: "machine-learning",
    tags: ["deep-learning", "neural-network", "gpu", "tensor"],
    featured: true,
    installCommand: "pip install torch",
    repositoryUrl: "https://github.com/pytorch/pytorch",
    documentationUrl: "https://pytorch.org",
    lastUpdated: "2025-12-05",
    pythonVersions: ["3.9", "3.10", "3.11", "3.12"],
    dependencies: ["typing-extensions", "sympy", "networkx", "jinja2"],
    longDescription: "PyTorch is an optimized tensor library for deep learning using GPUs and CPUs. It provides Tensor computation with strong GPU acceleration, deep neural networks built on a tape-based autograd system, and is widely used in both research and production environments.",
  },
  {
    name: "TensorFlow",
    slug: "tensorflow",
    description: "An open-source machine learning framework for everyone. Production-grade ML platform.",
    version: "2.18.0",
    author: "Google Brain Team",
    license: "Apache-2.0",
    downloads: "15.2M",
    category: "machine-learning",
    tags: ["deep-learning", "neural-network", "production"],
    featured: false,
    installCommand: "pip install tensorflow",
    repositoryUrl: "https://github.com/tensorflow/tensorflow",
    documentationUrl: "https://www.tensorflow.org",
    lastUpdated: "2025-11-01",
    pythonVersions: ["3.9", "3.10", "3.11", "3.12"],
    dependencies: ["numpy", "protobuf", "grpcio", "absl-py"],
    longDescription: "TensorFlow is an end-to-end open source platform for machine learning. It has a comprehensive, flexible ecosystem of tools, libraries and community resources that lets researchers push the state-of-the-art in ML and developers easily build and deploy ML powered applications.",
  },
  {
    name: "Hugging Face Transformers",
    slug: "transformers",
    description: "State-of-the-art Machine Learning for PyTorch, TensorFlow, and JAX.",
    version: "4.47.1",
    author: "Hugging Face",
    license: "Apache-2.0",
    downloads: "21.5M",
    category: "machine-learning",
    tags: ["nlp", "transformers", "llm", "pretrained"],
    featured: false,
    installCommand: "pip install transformers",
    repositoryUrl: "https://github.com/huggingface/transformers",
    documentationUrl: "https://huggingface.co/docs/transformers",
    lastUpdated: "2025-12-12",
    pythonVersions: ["3.8", "3.9", "3.10", "3.11", "3.12"],
    dependencies: ["numpy", "tokenizers", "safetensors", "huggingface-hub"],
    longDescription: "Transformers provides thousands of pretrained models to perform tasks on different modalities such as text, vision, and audio. These models can be applied to text generation, classification, translation, question answering, object detection, image segmentation, and more.",
  },
  {
    name: "Docker SDK",
    slug: "docker-sdk",
    description: "A Python library for the Docker Engine API. Manage containers programmatically.",
    version: "7.1.0",
    author: "Docker Inc.",
    license: "Apache-2.0",
    downloads: "9.4M",
    category: "devops",
    tags: ["docker", "containers", "infrastructure"],
    featured: false,
    installCommand: "pip install docker",
    repositoryUrl: "https://github.com/docker/docker-py",
    documentationUrl: "https://docker-py.readthedocs.io",
    lastUpdated: "2025-08-15",
    pythonVersions: ["3.8", "3.9", "3.10", "3.11", "3.12"],
    dependencies: ["requests", "urllib3", "websocket-client"],
    longDescription: "Docker SDK for Python is a Python library for the Docker Engine API. It lets you do anything the docker command does, but from within Python apps. Build, manage, and monitor containers, images, and services all from Python.",
  },
  {
    name: "Ansible",
    slug: "ansible",
    description: "Radically simple IT automation. Automate cloud provisioning, configuration management.",
    version: "10.7.0",
    author: "Red Hat",
    license: "GPL-3.0",
    downloads: "6.8M",
    category: "devops",
    tags: ["automation", "infrastructure", "provisioning"],
    featured: false,
    installCommand: "pip install ansible",
    repositoryUrl: "https://github.com/ansible/ansible",
    documentationUrl: "https://docs.ansible.com",
    lastUpdated: "2025-10-12",
    pythonVersions: ["3.10", "3.11", "3.12"],
    dependencies: ["jinja2", "pyyaml", "cryptography"],
    longDescription: "Ansible is a radically simple IT automation engine that automates cloud provisioning, configuration management, application deployment, intra-service orchestration, and many other IT needs.",
  },
  {
    name: "Fabric",
    slug: "fabric",
    description: "Simple, Pythonic remote execution and deployment. Execute shell commands remotely.",
    version: "3.2.2",
    author: "Jeff Forcier",
    license: "BSD-2-Clause",
    downloads: "4.1M",
    category: "devops",
    tags: ["ssh", "deployment", "automation"],
    featured: false,
    installCommand: "pip install fabric",
    repositoryUrl: "https://github.com/fabric/fabric",
    documentationUrl: "https://www.fabfile.org",
    lastUpdated: "2025-07-20",
    pythonVersions: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11", "3.12"],
    dependencies: ["invoke", "paramiko"],
    longDescription: "Fabric is a high level Python library designed to execute shell commands remotely over SSH, yielding useful Python objects in return. It builds on top of Invoke for command execution and Paramiko for SSH functionality.",
  },
  {
    name: "pytest",
    slug: "pytest",
    description: "Simple powerful testing with Python. The pytest framework makes it easy to write small tests.",
    version: "8.3.4",
    author: "Holger Krekel and pytest-dev team",
    license: "MIT",
    downloads: "65.2M",
    category: "testing",
    tags: ["testing", "unit-test", "fixtures"],
    featured: true,
    installCommand: "pip install pytest",
    repositoryUrl: "https://github.com/pytest-dev/pytest",
    documentationUrl: "https://docs.pytest.org",
    lastUpdated: "2025-11-25",
    pythonVersions: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"],
    dependencies: ["iniconfig", "packaging", "pluggy"],
    longDescription: "The pytest framework makes it easy to write small, readable tests, and can scale to support complex functional testing for applications and libraries. Features include detailed info on failing assert statements, auto-discovery of test modules, modular fixtures, and a rich plugin architecture.",
  },
  {
    name: "Hypothesis",
    slug: "hypothesis",
    description: "Property-based testing for Python. Automatically generates test cases for you.",
    version: "6.119.3",
    author: "David MacIver",
    license: "MPL-2.0",
    downloads: "8.9M",
    category: "testing",
    tags: ["property-testing", "fuzzing", "generative"],
    featured: false,
    installCommand: "pip install hypothesis",
    repositoryUrl: "https://github.com/HypothesisWorks/hypothesis",
    documentationUrl: "https://hypothesis.readthedocs.io",
    lastUpdated: "2025-12-08",
    pythonVersions: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"],
    dependencies: ["attrs", "sortedcontainers"],
    longDescription: "Hypothesis is a family of testing libraries which let you write tests parameterized by a source of examples. A Hypothesis test works by generating random data matching your specification and checking that your guarantee still holds in that case.",
  },
  {
    name: "tox",
    slug: "tox",
    description: "Command line driven CI frontend and development task automation tool.",
    version: "4.23.2",
    author: "tox-dev team",
    license: "MIT",
    downloads: "12.7M",
    category: "testing",
    tags: ["ci", "automation", "virtualenv"],
    featured: false,
    installCommand: "pip install tox",
    repositoryUrl: "https://github.com/tox-dev/tox",
    documentationUrl: "https://tox.wiki",
    lastUpdated: "2025-09-10",
    pythonVersions: ["3.8", "3.9", "3.10", "3.11", "3.12"],
    dependencies: ["packaging", "pluggy", "virtualenv"],
    longDescription: "tox aims to automate and standardize testing in Python. It is part of a larger vision of easing the packaging, testing and release process of Python software. tox can be used for testing with multiple Python versions and configurations.",
  },
  {
    name: "Click",
    slug: "click",
    description: "Composable command line interface toolkit. Create beautiful CLIs in a composable way.",
    version: "8.1.7",
    author: "Pallets",
    license: "BSD-3-Clause",
    downloads: "56.3M",
    category: "cli-tools",
    tags: ["cli", "commands", "terminal"],
    featured: false,
    installCommand: "pip install click",
    repositoryUrl: "https://github.com/pallets/click",
    documentationUrl: "https://click.palletsprojects.com",
    lastUpdated: "2025-06-15",
    pythonVersions: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"],
    dependencies: [],
    longDescription: "Click is a Python package for creating beautiful command line interfaces in a composable way with as little code as necessary. It is the command line interface creation kit that is highly configurable and comes with sensible defaults out of the box.",
  },
  {
    name: "Typer",
    slug: "typer",
    description: "Build great CLIs. Easy to code. Based on Python type hints.",
    version: "0.15.1",
    author: "Sebastian Ramirez",
    license: "MIT",
    downloads: "7.6M",
    category: "cli-tools",
    tags: ["cli", "type-hints", "modern"],
    featured: false,
    installCommand: "pip install typer",
    repositoryUrl: "https://github.com/tiangolo/typer",
    documentationUrl: "https://typer.tiangolo.com",
    lastUpdated: "2025-11-08",
    pythonVersions: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"],
    dependencies: ["click", "rich", "shellingham"],
    longDescription: "Typer is a library for building CLI applications that users will love using and developers will love creating. Based on Python type hints. It is the FastAPI of CLIs - featuring editor support, automatic help text, and validation out of the box.",
  },
  {
    name: "Rich",
    slug: "rich",
    description: "Rich text and beautiful formatting in the terminal. Write rich console output.",
    version: "13.9.4",
    author: "Will McGugan",
    license: "MIT",
    downloads: "34.8M",
    category: "cli-tools",
    tags: ["terminal", "formatting", "console", "color"],
    featured: false,
    installCommand: "pip install rich",
    repositoryUrl: "https://github.com/Textualize/rich",
    documentationUrl: "https://rich.readthedocs.io",
    lastUpdated: "2025-10-20",
    pythonVersions: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"],
    dependencies: ["markdown-it-py", "pygments"],
    longDescription: "Rich is a Python library for rich text and beautiful formatting in the terminal. The Rich API makes it easy to add color and style to terminal output. Rich can also render pretty tables, progress bars, markdown, syntax highlighted source code, tracebacks, and more.",
  },
  {
    name: "SQLAlchemy",
    slug: "sqlalchemy",
    description: "The Python SQL Toolkit and Object Relational Mapper. Full power of SQL in Python.",
    version: "2.0.36",
    author: "Mike Bayer",
    license: "MIT",
    downloads: "52.4M",
    category: "database",
    tags: ["sql", "orm", "database", "query"],
    featured: true,
    installCommand: "pip install sqlalchemy",
    repositoryUrl: "https://github.com/sqlalchemy/sqlalchemy",
    documentationUrl: "https://www.sqlalchemy.org",
    lastUpdated: "2025-12-02",
    pythonVersions: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12", "3.13"],
    dependencies: ["typing-extensions"],
    longDescription: "SQLAlchemy is the Python SQL toolkit and Object Relational Mapper that gives application developers the full power and flexibility of SQL. It provides a full suite of well known enterprise-level persistence patterns, designed for efficient and high-performing database access.",
  },
  {
    name: "Alembic",
    slug: "alembic",
    description: "A database migration tool for SQLAlchemy. Manage schema changes with ease.",
    version: "1.14.0",
    author: "Mike Bayer",
    license: "MIT",
    downloads: "18.9M",
    category: "database",
    tags: ["migration", "schema", "database"],
    featured: false,
    installCommand: "pip install alembic",
    repositoryUrl: "https://github.com/sqlalchemy/alembic",
    documentationUrl: "https://alembic.sqlalchemy.org",
    lastUpdated: "2025-09-25",
    pythonVersions: ["3.8", "3.9", "3.10", "3.11", "3.12"],
    dependencies: ["sqlalchemy", "mako"],
    longDescription: "Alembic is a lightweight database migration tool for usage with the SQLAlchemy Database Toolkit for Python. It provides schema change management for relational databases, with support for creating, applying, and reverting database migrations.",
  },
  {
    name: "Tortoise ORM",
    slug: "tortoise-orm",
    description: "Easy async ORM for Python, built with relations in mind. Inspired by Django ORM.",
    version: "0.22.1",
    author: "Tortoise team",
    license: "Apache-2.0",
    downloads: "2.1M",
    category: "database",
    tags: ["orm", "async", "database"],
    featured: false,
    installCommand: "pip install tortoise-orm",
    repositoryUrl: "https://github.com/tortoise/tortoise-orm",
    documentationUrl: "https://tortoise.github.io",
    lastUpdated: "2025-08-03",
    pythonVersions: ["3.8", "3.9", "3.10", "3.11", "3.12"],
    dependencies: ["aiosqlite", "pypika-tortoise"],
    longDescription: "Tortoise ORM is an easy-to-use asyncio ORM (Object Relational Mapper) inspired by Django. It supports relation fields, comprehensive filtering, and is designed for use with async Python applications.",
  },
]

export function getPackagesByCategory(categorySlug: string): Package[] {
  if (categorySlug === "all") return packages
  return packages.filter((pkg) => pkg.category === categorySlug)
}

export function getPackageBySlug(slug: string): Package | undefined {
  return packages.find((pkg) => pkg.slug === slug)
}

export function getFeaturedPackages(): Package[] {
  return packages.filter((pkg) => pkg.featured)
}

export function searchPackages(query: string): Package[] {
  const lowerQuery = query.toLowerCase()
  return packages.filter(
    (pkg) =>
      pkg.name.toLowerCase().includes(lowerQuery) ||
      pkg.description.toLowerCase().includes(lowerQuery) ||
      pkg.tags.some((tag) => tag.toLowerCase().includes(lowerQuery))
  )
}

export function formatDownloads(downloads: string): string {
  return `${downloads}/month`
}
